
server:
  # ===================================================================
  # 端口号
  # ===================================================================
  port: 9001
  # ===================================================================
  # springboot内置Tomcat优化配置
  # ===================================================================
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 10
  # ===================================================================
  # 服务器链接超时
  # ===================================================================
  connection-timeout: 5000ms

spring:
  # ===================================================================
  # 项目名称
  # ===================================================================
  application:
    name: tensquare-base

  # ===================================================================
  # springboot中配置springmvc异常抛出
  # ===================================================================
#  mvc:
#    throw-exception-if-no-handler-found: true

  # ===================================================================
  # MySQL数据库连接配置
  # ===================================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.179.131:3306/tensquare_base?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  # ===================================================================
  # DAO层 JPA配置
  # ===================================================================
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false   # 禁用视图，解决启动 warm 警告

# ===================================================================
# logger 日志 配置
# ===================================================================
logging:
  file:
    max-history: 10
    max-size: 10MB
  path: tensquare_base
