server:
  # ===================================================================
  # 端口号
  # ===================================================================
  port: 12000
spring:
  # ===================================================================
  # 项目名称
  # ===================================================================
  application:
    name: tensquare-config
  # ===================================================================
  # spring-cloud-config 配置中心服务
  # ===================================================================
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Freya0016/tensquare-config.git