server:
  # ===================================================================
  # 端口号
  # ===================================================================
  port: 12000
spring:
  # ===================================================================
  # 项目名称
  # ===================================================================
  application:
    name: tensquare-config
  # ===================================================================
  # spring-cloud-config 配置中心服务
  # ===================================================================
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Freya0016/tensquare-config.git
  # ===================================================================
  # spring-cloud-bus rabbitmq 配置
  # ===================================================================
  rabbitmq:
    host: 192.168.179.132
# ===================================================================
# spring-cloud-bus 配置中心服务 消息总线
# ===================================================================
management:   # 暴露触发消息总线刷新的节点地址
  endpoints:
    web:
      exposure:
        include: bus-refresh